// <auto-generated />
namespace cecati_117.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fullUserName_accunt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fullUserName_accunt));
        
        string IMigrationMetadata.Id
        {
            get { return "201808180203316_fullUserName_accunt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
