// <auto-generated />
namespace cecati_117.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class galeria_change3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(galeria_change3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806290122381_galeria_change3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
